name: Build-Docker-images-macos

on:
  push:
    branches: [ "main" ]
    paths:
      - "**/Docker/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "**/Docker/**"
  
jobs:
  build:
    runs-on: macos-latest
    
    strategy:
      fail-fast: false
      matrix:
        platform:
          - darwin
    
    # Build the docker images 
    steps:
    
      - name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV          
      
      # Add docker multiplatform build
      - name: Set up qemu Action
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Check out the code
        uses: actions/checkout@v4
      
      - name: docker-compose Build Action
        run: COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker compose -f Docker/docker-compose.yaml build
      
      - name: docker-compose Push Action
        run: COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker compose -f Docker/docker-compose.yaml push
      
      